"""add_wilayah_and_dinas_admin

Revision ID: 109041695d3d
Revises: ff366ad23bce
Create Date: 2026-08-23 10:04:50.865184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109041695d3d'
down_revision: Union[str, None] = 'ff366ad23bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kabupaten_kota',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('provinsi', sa.String(length=100), nullable=False),
    sa.Column('kode_kemendagri', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_kemendagri')
    )
    op.create_table('dinas_admin',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kabupaten_id', sa.UUID(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kabupaten_id'], ['kabupaten_kota.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_dinas_admin_kabupaten', 'dinas_admin', ['kabupaten_id'], unique=False)
    op.drop_table('dinas_sekolah_binaan')
    op.add_column('sekolah', sa.Column('kabupaten_id', sa.UUID(), nullable=True, comment='ID Kabupaten/Kota wilayah sekolah'))
    op.create_foreign_key(None, 'sekolah', 'kabupaten_kota', ['kabupaten_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sekolah', type_='foreignkey')
    op.drop_column('sekolah', 'kabupaten_id')
    op.create_table('dinas_sekolah_binaan',
    sa.Column('dinas_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sekolah_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dinas_id'], ['admin.id'], name=op.f('dinas_sekolah_binaan_dinas_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], name=op.f('dinas_sekolah_binaan_sekolah_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dinas_id', 'sekolah_id', name=op.f('dinas_sekolah_binaan_pkey'))
    )
    op.drop_index('idx_dinas_admin_kabupaten', table_name='dinas_admin')
    op.drop_table('dinas_admin')
    op.drop_table('kabupaten_kota')
    # ### end Alembic commands ###
