"""create_backup_tables

Revision ID: db16f4c7afb3
Revises: 006_add_retention_legal_hold
Create Date: 2026-08-27 06:25:07.578634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db16f4c7afb3'
down_revision: Union[str, None] = '006_add_retention_legal_hold'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_records',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text('gen_random_uuid()')),
        sa.Column('nama_file', sa.String(200), nullable=False),
        sa.Column('ukuran_bytes', sa.BigInteger, nullable=False),
        sa.Column('checksum_sha256', sa.String(64), nullable=False),
        sa.Column('manifest_json', postgresql.JSONB, nullable=False,
                  server_default='{}'),
        sa.Column('status', sa.String(20), nullable=False, server_default='pending'),
        sa.Column('tipe', sa.String(20), nullable=False, server_default='manual'),
        sa.Column('storage_path', sa.Text, nullable=True),
        sa.Column('dibuat_oleh', sa.Integer,
                  sa.ForeignKey('admin.id', ondelete='SET NULL'), nullable=True),
        sa.Column('restored_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('restored_by', sa.Integer,
                  sa.ForeignKey('admin.id', ondelete='SET NULL'), nullable=True),
        sa.Column('error_message', sa.Text, nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                  nullable=False, server_default=sa.text('NOW()')),
        sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.create_index('idx_backup_status', 'backup_records', ['status'])
    op.create_index('idx_backup_created', 'backup_records', ['created_at'])

    op.alter_column('dokumen', 'legal_hold',
               existing_type=sa.BOOLEAN(),
               comment='Apakah dokumen ini dalam status Legal Hold (dilindungi dari hapus/archive)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('dokumen', 'legal_hold_by',
               existing_type=sa.INTEGER(),
               comment='FK ke admin yang menetapkan legal hold',
               existing_nullable=True)
    op.alter_column('dokumen', 'legal_hold_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Waktu legal hold ditetapkan (UTC)',
               existing_nullable=True)
    op.alter_column('dokumen', 'legal_hold_alasan',
               existing_type=sa.TEXT(),
               comment='Alasan penetapan legal hold',
               existing_nullable=True)
    op.alter_column('dokumen', 'retention_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Waktu dokumen kadaluarsa berdasarkan retention policy (UTC)',
               existing_nullable=True)
    op.drop_index(op.f('idx_dokumen_legal_hold_active'), table_name='dokumen', postgresql_where='(legal_hold = true)')
    op.drop_index(op.f('idx_dokumen_retention_expires'), table_name='dokumen', postgresql_where='(legal_hold = false)')
    op.alter_column('retention_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.create_table_comment(
        'retention_log',
        'Log histori aksi retensi (immutable)',
        existing_comment='Log histori setiap aksi retensi (immutable)',
        schema=None
    )
    op.alter_column('retention_policy', 'sekolah_id',
               existing_type=sa.INTEGER(),
               comment='FK ke sekolah pemilik kebijakan',
               existing_nullable=False)
    op.alter_column('retention_policy', 'jenis_dok',
               existing_type=sa.VARCHAR(length=100),
               comment='Jenis dokumen yang diatur (rapor, ijazah, dll)',
               existing_nullable=False)
    op.alter_column('retention_policy', 'durasi_hari',
               existing_type=sa.INTEGER(),
               comment='Durasi retensi dalam hari sejak upload',
               existing_nullable=False,
               existing_server_default=sa.text('1825'))
    op.alter_column('retention_policy', 'aksi_setelah',
               existing_type=sa.VARCHAR(length=20),
               comment='Aksi setelah expired: archive | delete | notify_only',
               existing_nullable=False,
               existing_server_default=sa.text("'archive'::character varying"))
    op.alter_column('retention_policy', 'notif_hari_sebelum',
               existing_type=sa.INTEGER(),
               comment='Kirim notifikasi N hari sebelum expired',
               existing_nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('retention_policy', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Apakah kebijakan ini aktif',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('retention_policy', 'created_by',
               existing_type=sa.INTEGER(),
               comment='FK ke admin yang membuat kebijakan',
               existing_nullable=True)
    op.alter_column('retention_policy', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('retention_policy', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sekolah', 'sindas_api_url',
               existing_type=sa.VARCHAR(length=255),
               comment='Link API SINDAS untuk sekolah ini',
               existing_nullable=True)
    op.alter_column('sekolah', 'sindas_api_key',
               existing_type=sa.VARCHAR(length=255),
               comment='API Key SINDAS untuk sekolah ini',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sekolah', 'sindas_api_key',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='API Key SINDAS untuk sekolah ini',
               existing_nullable=True)
    op.alter_column('sekolah', 'sindas_api_url',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Link API SINDAS untuk sekolah ini',
               existing_nullable=True)
    op.alter_column('retention_policy', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('retention_policy', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('retention_policy', 'created_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK ke admin yang membuat kebijakan',
               existing_nullable=True)
    op.alter_column('retention_policy', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Apakah kebijakan ini aktif',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('retention_policy', 'notif_hari_sebelum',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Kirim notifikasi N hari sebelum expired',
               existing_nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('retention_policy', 'aksi_setelah',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Aksi setelah expired: archive | delete | notify_only',
               existing_nullable=False,
               existing_server_default=sa.text("'archive'::character varying"))
    op.alter_column('retention_policy', 'durasi_hari',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Durasi retensi dalam hari sejak upload',
               existing_nullable=False,
               existing_server_default=sa.text('1825'))
    op.alter_column('retention_policy', 'jenis_dok',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Jenis dokumen yang diatur (rapor, ijazah, dll)',
               existing_nullable=False)
    op.alter_column('retention_policy', 'sekolah_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK ke sekolah pemilik kebijakan',
               existing_nullable=False)
    op.create_table_comment(
        'retention_log',
        'Log histori setiap aksi retensi (immutable)',
        existing_comment='Log histori aksi retensi (immutable)',
        schema=None
    )
    op.alter_column('retention_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('idx_dokumen_retention_expires'), 'dokumen', ['retention_expires_at'], unique=False, postgresql_where='(legal_hold = false)')
    op.create_index(op.f('idx_dokumen_legal_hold_active'), 'dokumen', ['legal_hold'], unique=False, postgresql_where='(legal_hold = true)')
    op.alter_column('dokumen', 'retention_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Waktu dokumen kadaluarsa berdasarkan retention policy (UTC)',
               existing_nullable=True)
    op.alter_column('dokumen', 'legal_hold_alasan',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Alasan penetapan legal hold',
               existing_nullable=True)
    op.alter_column('dokumen', 'legal_hold_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Waktu legal hold ditetapkan (UTC)',
               existing_nullable=True)
    op.alter_column('dokumen', 'legal_hold_by',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='FK ke admin yang menetapkan legal hold',
               existing_nullable=True)
    op.alter_column('dokumen', 'legal_hold',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Apakah dokumen ini dalam status Legal Hold (dilindungi dari hapus/archive)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_table('backup_records')
    # ### end Alembic commands ###
